//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.21 at 05:14:44 PM CEST 
//


package pl.coderstrust.soapinvoices;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AddressWS complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="AddressWS">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="zipCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="townName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="streetName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="houseNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AddressWS", propOrder = {
    "zipCode",
    "townName",
    "streetName",
    "houseNumber"
})
public class AddressWS {

  @XmlElement(required = true)
  protected String zipCode;
  @XmlElement(required = true)
  protected String townName;
  @XmlElement(required = true)
  protected String streetName;
  @XmlElement(required = true)
  protected String houseNumber;

  /**
   * Gets the value of the zipCode property.
   *
   * @return possible object is {@link String }
   */
  public String getZipCode() {
    return zipCode;
  }

  /**
   * Sets the value of the zipCode property.
   *
   * @param value allowed object is {@link String }
   */
  public void setZipCode(String value) {
    this.zipCode = value;
  }

  /**
   * Gets the value of the townName property.
   *
   * @return possible object is {@link String }
   */
  public String getTownName() {
    return townName;
  }

  /**
   * Sets the value of the townName property.
   *
   * @param value allowed object is {@link String }
   */
  public void setTownName(String value) {
    this.townName = value;
  }

  /**
   * Gets the value of the streetName property.
   *
   * @return possible object is {@link String }
   */
  public String getStreetName() {
    return streetName;
  }

  /**
   * Sets the value of the streetName property.
   *
   * @param value allowed object is {@link String }
   */
  public void setStreetName(String value) {
    this.streetName = value;
  }

  /**
   * Gets the value of the houseNumber property.
   *
   * @return possible object is {@link String }
   */
  public String getHouseNumber() {
    return houseNumber;
  }

  /**
   * Sets the value of the houseNumber property.
   *
   * @param value allowed object is {@link String }
   */
  public void setHouseNumber(String value) {
    this.houseNumber = value;
  }

}
