//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.21 at 05:14:44 PM CEST 
//


package pl.coderstrust.soapinvoices;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CounterpartyWS complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="CounterpartyWS">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="companyName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="address" type="{http://coderstrust.pl/soapinvoices}AddressWS"/>
 *         &lt;element name="phoneNumber" type="{http://coderstrust.pl/soapinvoices}phoneNumber"/>
 *         &lt;element name="nip" type="{http://coderstrust.pl/soapinvoices}Nip"/>
 *         &lt;element name="bankName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="bankNumber" type="{http://coderstrust.pl/soapinvoices}BankNumber"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CounterpartyWS", propOrder = {
    "companyName",
    "address",
    "phoneNumber",
    "nip",
    "bankName",
    "bankNumber"
})
public class CounterpartyWS {

  @XmlElement(required = true)
  protected String companyName;
  @XmlElement(required = true)
  protected AddressWS address;
  @XmlElement(required = true)
  protected String phoneNumber;
  @XmlElement(required = true)
  protected String nip;
  @XmlElement(required = true)
  protected String bankName;
  @XmlElement(required = true)
  protected String bankNumber;

  /**
   * Gets the value of the companyName property.
   *
   * @return possible object is {@link String }
   */
  public String getCompanyName() {
    return companyName;
  }

  /**
   * Sets the value of the companyName property.
   *
   * @param value allowed object is {@link String }
   */
  public void setCompanyName(String value) {
    this.companyName = value;
  }

  /**
   * Gets the value of the address property.
   *
   * @return possible object is {@link AddressWS }
   */
  public AddressWS getAddress() {
    return address;
  }

  /**
   * Sets the value of the address property.
   *
   * @param value allowed object is {@link AddressWS }
   */
  public void setAddress(AddressWS value) {
    this.address = value;
  }

  /**
   * Gets the value of the phoneNumber property.
   *
   * @return possible object is {@link String }
   */
  public String getPhoneNumber() {
    return phoneNumber;
  }

  /**
   * Sets the value of the phoneNumber property.
   *
   * @param value allowed object is {@link String }
   */
  public void setPhoneNumber(String value) {
    this.phoneNumber = value;
  }

  /**
   * Gets the value of the nip property.
   *
   * @return possible object is {@link String }
   */
  public String getNip() {
    return nip;
  }

  /**
   * Sets the value of the nip property.
   *
   * @param value allowed object is {@link String }
   */
  public void setNip(String value) {
    this.nip = value;
  }

  /**
   * Gets the value of the bankName property.
   *
   * @return possible object is {@link String }
   */
  public String getBankName() {
    return bankName;
  }

  /**
   * Sets the value of the bankName property.
   *
   * @param value allowed object is {@link String }
   */
  public void setBankName(String value) {
    this.bankName = value;
  }

  /**
   * Gets the value of the bankNumber property.
   *
   * @return possible object is {@link String }
   */
  public String getBankNumber() {
    return bankNumber;
  }

  /**
   * Sets the value of the bankNumber property.
   *
   * @param value allowed object is {@link String }
   */
  public void setBankNumber(String value) {
    this.bankNumber = value;
  }

}
