//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.21 at 05:14:44 PM CEST 
//


package pl.coderstrust.soapinvoices;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="selectByDate" type="{http://coderstrust.pl/soapinvoices}selectByDate"
 * minOccurs="0"/>
 *         &lt;element name="selectByYearAndMonth" type="{http://coderstrust.pl/soapinvoices}selectByYearAndMonth"
 * minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "selectByDate",
    "selectByYearAndMonth"
})
@XmlRootElement(name = "getInvoicesRequest")
public class GetInvoicesRequest {

  protected SelectByDate selectByDate;
  protected SelectByYearAndMonth selectByYearAndMonth;

  /**
   * Gets the value of the selectByDate property.
   *
   * @return possible object is {@link SelectByDate }
   */
  public SelectByDate getSelectByDate() {
    return selectByDate;
  }

  /**
   * Sets the value of the selectByDate property.
   *
   * @param value allowed object is {@link SelectByDate }
   */
  public void setSelectByDate(SelectByDate value) {
    this.selectByDate = value;
  }

  /**
   * Gets the value of the selectByYearAndMonth property.
   *
   * @return possible object is {@link SelectByYearAndMonth }
   */
  public SelectByYearAndMonth getSelectByYearAndMonth() {
    return selectByYearAndMonth;
  }

  /**
   * Sets the value of the selectByYearAndMonth property.
   *
   * @param value allowed object is {@link SelectByYearAndMonth }
   */
  public void setSelectByYearAndMonth(SelectByYearAndMonth value) {
    this.selectByYearAndMonth = value;
  }

}
