//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.21 at 05:14:44 PM CEST 
//


package pl.coderstrust.soapinvoices;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import java.math.BigDecimal;


/**
 * <p>Java class for invoiceItemWS complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="invoiceItemWS">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="numberOfItem" type="{http://coderstrust.pl/soapinvoices}NumberOfItem"/>
 *         &lt;element name="amount" type="{http://coderstrust.pl/soapinvoices}Amount"/>
 *         &lt;element name="vatAmount" type="{http://coderstrust.pl/soapinvoices}VatAmount"/>
 *         &lt;element name="vat" type="{http://coderstrust.pl/soapinvoices}VatWS"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "invoiceItemWS", propOrder = {
    "description",
    "numberOfItem",
    "amount",
    "vatAmount",
    "vat"
})
public class InvoiceItemWS {

  @XmlElement(required = true)
  protected String description;
  protected int numberOfItem;
  @XmlElement(required = true)
  protected BigDecimal amount;
  @XmlElement(required = true)
  protected BigDecimal vatAmount;
  @XmlElement(required = true)
  protected VatWS vat;

  /**
   * Gets the value of the description property.
   *
   * @return possible object is {@link String }
   */
  public String getDescription() {
    return description;
  }

  /**
   * Sets the value of the description property.
   *
   * @param value allowed object is {@link String }
   */
  public void setDescription(String value) {
    this.description = value;
  }

  /**
   * Gets the value of the numberOfItem property.
   */
  public int getNumberOfItem() {
    return numberOfItem;
  }

  /**
   * Sets the value of the numberOfItem property.
   */
  public void setNumberOfItem(int value) {
    this.numberOfItem = value;
  }

  /**
   * Gets the value of the amount property.
   *
   * @return possible object is {@link BigDecimal }
   */
  public BigDecimal getAmount() {
    return amount;
  }

  /**
   * Sets the value of the amount property.
   *
   * @param value allowed object is {@link BigDecimal }
   */
  public void setAmount(BigDecimal value) {
    this.amount = value;
  }

  /**
   * Gets the value of the vatAmount property.
   *
   * @return possible object is {@link BigDecimal }
   */
  public BigDecimal getVatAmount() {
    return vatAmount;
  }

  /**
   * Sets the value of the vatAmount property.
   *
   * @param value allowed object is {@link BigDecimal }
   */
  public void setVatAmount(BigDecimal value) {
    this.vatAmount = value;
  }

  /**
   * Gets the value of the vat property.
   *
   * @return possible object is {@link VatWS }
   */
  public VatWS getVat() {
    return vat;
  }

  /**
   * Sets the value of the vat property.
   *
   * @param value allowed object is {@link VatWS }
   */
  public void setVat(VatWS value) {
    this.vat = value;
  }

}
