//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.21 at 05:14:44 PM CEST 
//


package pl.coderstrust.soapinvoices;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for InvoiceBodyWS complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="InvoiceBodyWS">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="counterparty" type="{http://coderstrust.pl/soapinvoices}CounterpartyWS"/>
 *         &lt;element name="itemsList" type="{http://coderstrust.pl/soapinvoices}invoiceItemWS"
 * maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InvoiceBodyWS", propOrder = {
    "date",
    "counterparty",
    "itemsList"
})
public class InvoiceBodyWS {

  @XmlElement(required = true)
  @XmlSchemaType(name = "date")
  protected XMLGregorianCalendar date;
  @XmlElement(required = true)
  protected CounterpartyWS counterparty;
  @XmlElement(required = true)
  protected List<InvoiceItemWS> itemsList;

  /**
   * Gets the value of the date property.
   *
   * @return possible object is {@link XMLGregorianCalendar }
   */
  public XMLGregorianCalendar getDate() {
    return date;
  }

  /**
   * Sets the value of the date property.
   *
   * @param value allowed object is {@link XMLGregorianCalendar }
   */
  public void setDate(XMLGregorianCalendar value) {
    this.date = value;
  }

  /**
   * Gets the value of the counterparty property.
   *
   * @return possible object is {@link CounterpartyWS }
   */
  public CounterpartyWS getCounterparty() {
    return counterparty;
  }

  /**
   * Sets the value of the counterparty property.
   *
   * @param value allowed object is {@link CounterpartyWS }
   */
  public void setCounterparty(CounterpartyWS value) {
    this.counterparty = value;
  }

  /**
   * Gets the value of the itemsList property.
   *
   * <p> This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the itemsList property.
   *
   * <p> For example, to add a new item, do as follows:
   * <pre>
   *    getItemsList().add(newItem);
   * </pre>
   *
   *
   * <p> Objects of the following type(s) are allowed in the list {@link InvoiceItemWS }
   */
  public List<InvoiceItemWS> getItemsList() {
    if (itemsList == null) {
      itemsList = new ArrayList<InvoiceItemWS>();
    }
    return this.itemsList;
  }

}
