////
//// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7
//// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
//// Any modifications to this file will be lost upon recompilation of the source schema.
//// Generated on: 2017.09.20 at 03:29:49 PM CEST
////
//
//
//package pl.coderstrust.soapinvoices;
//
//import javax.xml.bind.annotation.XmlEnum;
//import javax.xml.bind.annotation.XmlType;
//
//
///**
// * <p>Java class for MonthXsd.
// *
// * <p>The following schema fragment specifies the expected content contained within this class.
// * <p>
// * <pre>
// * &lt;simpleType name="MonthXsd">
// *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
// *     &lt;pattern value="[A-Z]*"/>
// *     &lt;enumeration value="JANUARY"/>
// *     &lt;enumeration value="FEBRUARY"/>
// *     &lt;enumeration value="MARCH"/>
// *     &lt;enumeration value="APRIL"/>
// *     &lt;enumeration value="MAY"/>
// *     &lt;enumeration value="JUNE"/>
// *     &lt;enumeration value="JULY"/>
// *     &lt;enumeration value="AUGUST"/>
// *     &lt;enumeration value="SEPTEMBER"/>
// *     &lt;enumeration value="OCTOBER"/>
// *     &lt;enumeration value="NOVEMBER"/>
// *     &lt;enumeration value="DECEMBER"/>
// *   &lt;/restriction>
// * &lt;/simpleType>
// * </pre>
// *
// */
//@XmlType(name = "MonthXsd")
//@XmlEnum
//public enum MonthXsd {
//
//    JANUARY,
//    FEBRUARY,
//    MARCH,
//    APRIL,
//    MAY,
//    JUNE,
//    JULY,
//    AUGUST,
//    SEPTEMBER,
//    OCTOBER,
//    NOVEMBER,
//    DECEMBER;
//
//    public String value() {
//        return name();
//    }
//
//    public static MonthXsd fromValue(String v) {
//        return valueOf(v);
//    }
//
//}
