//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.21 at 05:14:44 PM CEST 
//


package pl.coderstrust.soapinvoices;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for selectByDate complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="selectByDate">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fromDate" type="{http://coderstrust.pl/soapinvoices}Date"/>
 *         &lt;element name="toDate" type="{http://coderstrust.pl/soapinvoices}Date"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "selectByDate", propOrder = {
    "fromDate",
    "toDate"
})
public class SelectByDate {

  @XmlElement(required = true)
  protected String fromDate;
  @XmlElement(required = true)
  protected String toDate;

  /**
   * Gets the value of the fromDate property.
   *
   * @return possible object is {@link String }
   */
  public String getFromDate() {
    return fromDate;
  }

  /**
   * Sets the value of the fromDate property.
   *
   * @param value allowed object is {@link String }
   */
  public void setFromDate(String value) {
    this.fromDate = value;
  }

  /**
   * Gets the value of the toDate property.
   *
   * @return possible object is {@link String }
   */
  public String getToDate() {
    return toDate;
  }

  /**
   * Sets the value of the toDate property.
   *
   * @param value allowed object is {@link String }
   */
  public void setToDate(String value) {
    this.toDate = value;
  }

}
