//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.21 at 05:14:44 PM CEST 
//


package pl.coderstrust.soapinvoices;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for selectByYearAndMonth complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="selectByYearAndMonth">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="year" type="{http://coderstrust.pl/soapinvoices}Year"/>
 *         &lt;element name="month" type="{http://coderstrust.pl/soapinvoices}MonthXsd"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "selectByYearAndMonth", propOrder = {
    "year",
    "month"
})
public class SelectByYearAndMonth {

  @XmlElement(defaultValue = "2017")
  protected int year;
  @XmlElement(required = true, defaultValue = "JANUARY")
  protected String month;

  /**
   * Gets the value of the year property.
   */
  public int getYear() {
    return year;
  }

  /**
   * Sets the value of the year property.
   */
  public void setYear(int value) {
    this.year = value;
  }

  /**
   * Gets the value of the month property.
   *
   * @return possible object is {@link String }
   */
  public String getMonth() {
    return month;
  }

  /**
   * Sets the value of the month property.
   *
   * @param value allowed object is {@link String }
   */
  public void setMonth(String value) {
    this.month = value;
  }

}
